# Generated by Django 5.2 on 2025-05-06 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0004_alter_customuser_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='revendedor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('verificado', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verificado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
