# Generated by Django 5.2 on 2025-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0005_revendedor_remove_customuser_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='cnpj_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
