# Generated by Django 5.2 on 2025-05-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0007_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
    ]
