# Generated by Django 5.2 on 2025-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0008_remove_supportticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
