# Generated by Django 5.2 on 2025-05-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
