# Generated by Django 5.2 on 2025-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0011_remove_ticketmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
