# Generated by Django 5.2.1 on 2025-06-08 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0012_alter_ticketmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('printer', 'Impressora 3D'), ('filament', 'Filamento'), ('accessory', 'Acessório'), ('part', 'Peça de Reposição')], default='printer', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('out_of_stock', 'Fora de Estoque'), ('discontinued', 'Descontinuado')], default='available', max_length=20)),
                ('build_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('layer_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('print_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('nozzle_diameter', models.CharField(blank=True, max_length=20, null=True)),
                ('filament_diameter', models.CharField(blank=True, max_length=20, null=True)),
                ('supported_materials', models.TextField(blank=True, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
