# Generated by Django 5.2.3 on 2025-07-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letrajato', '0013_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Letrajato_files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('printer', 'Impressora 3D'), ('filament', 'Filamento'), ('accessory', 'Acessório'), ('part', 'Peça de Reposição')], default='Impressora 3D', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('out_of_stock', 'Fora de Estoque'), ('discontinued', 'Descontinuado')], default='Disponível', max_length=20),
        ),
    ]
